apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30001  # You can specify a port in the range 30000-32767
  selector:
    app: puzzlecoder-backend
